---
abstract: 'Parse record-oriented data in a text file'
author:
  - 'Ken Youens-Clark <kclark@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-RecordParser
no_index:
  directory:
    - inc
    - t
recommends:
  GraphViz: 0
  Text::TabularDisplay: '1.22'
requires:
  Class::Accessor: 0
  IO::Scalar: 0
  List::MoreUtils: 0
  List::Util: 0
  Readonly: 0
  Text::Autoformat: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: '1.006005'
